endpoints:
  actuator:
    sensitive: true
    enabled: true
management:
  context-path: /mgmt
spring:
  datasource:
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
security:
  user:
    name: deivee
    password: deivee


